### ISSUE TITLE
Combine field form and raw data form

### ISSUE THREAD

**Issue by jess-shue** [SCBI-ForestGEO/Dendrobands#90]
@jenajordan @teixeirak We would like to combine the necessary columns from the field form and the raw data form to create 'one form to rule them all' - this would be used for data collection in the field with an iPad, but also could be printed if necessary. We're hoping to streamline the process a bit as Bert and Jen have already done to some extent last year. 
Main questions:
- How to handle the date, personnel, and surveyID that are currently all in a column header for the field form
- Codes and notes as separate columns
- Maintain a 'paper' version for printing as needed that includes the most recent previous measurement

Proposed ideas:
- MM.NEW is the gap measurement and the 'NEW' would be the surveyID (would need code to extract this number)
- On the iPad, having a 'date' and 'personnel' column:  enter values once and copy and paste them down the column

Proposed columns to include:
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/jessh/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/jessh/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72" lang=EN-US style='tab-interval:.5in;
word-wrap:break-word'>

tag | stem | sp | dbh | quadrat | lx | ly | prev     measure | MM.NEW | codes | notes | date | personnel | area | location
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
10671 | 1 | quru | 851 | 114 | 6.2 | 14.5 | 70.83 |   |   |   |   |   | 3 | S

</body>

</html>

**Comment by teixeirak** [comment]
This looks fine to me.

**Comment by rudeboybert** [comment]
Note: this form would also require the `measure_verified` column we added in 2021 for situations where the original `measure` = `MM.NEW` was reverified in field after being alerted to be anomalous

**Comment by jenajordan** [comment]
Looks good. 'One form to rule them all' is good progress, with inclusion of the measure_verified column. Thanks! Jen

**Comment by rudeboybert** [comment]
Hey @jess-shue take a look at the follow spring biannual raw-data forms (with differences in columns in bold)

1. The [previous 2021 version](https://github.com/SCBI-ForestGEO/Dendrobands/blob/testing-2022/resources/raw_data/2021/data_entry_biannual_spr2021.csv): tag, stemtag, sp, quadrat, survey.ID, year, month, day, measure, new.band, **crown.condition**, **crown.illum**, codes, notes, field.recorders, data.enter, area 
2. My [preliminary 2022 version](https://github.com/SCBI-ForestGEO/Dendrobands/blob/testing-2022/resources/raw_data/data_entry_biannual_spr2022_BLANK.csv): survey.ID, year, month, day, field.recorders, data.enter, tag, stemtag, sp, dbh, quadrat, lx, ly, area, **location**, **previous_measure**, new.band, measure, **measure_verified**, codes, notes

To respond to your comments/suggestions:
1. While your proposed formats for `MM.NEW` and `date` actually make more sense to me, for legacy and backwards compatibility reasons I think they won't work at SCBI; I feel it would be easier to just keep `survey.ID` and `year, month, day`
1. I noticed that for any given survey, `survey.ID, year, month, day` don't change and furthermore `field.recorder, data.enter` are variables that don't need to be recorded in the field. Thus I put them in the far-left columns so that field technicians can delete these variables on paper/iPad for the field, but then fill them in once back on a computer.
1. Then I put all variables that help identify a stem
1. Lastly, I put all variables where field technicians actually need to record something on the far-right

Let me know how this preliminary 2022 version looks to you or if you want something changed (like column ordering). Note that some of the "previous_measure" values are NA; I think those relate to dead stems and/or bands with code RE.

**Comment by jess-shue** [comment]
@rudeboybert  Thanks for bringing up **crown.condition** and **crown.illum**; I had meant to ask @teixeirak if those fields should be recorded - we've ignored them the last few times I've assisted with measurements.

1. Sounds good, I was worried about it being too much of a change to the previous format as well.
2. I would default to the order I had the columns in my previous post with the  `survey.ID, year, month, day, field.recorder, data.enter` on the far right of the other columns. But, that's just coming from how I currently do things! I would err on keeping the columns in the data rather than having them deleted.

@jenajordan How does Bert's [preliminary 2022 version](https://github.com/SCBI-ForestGEO/Dendrobands/blob/testing-2022/resources/raw_data/data_entry_biannual_spr2022_BLANK.csv) look to you? Any thoughts on column order/placement and keeping or deleting the relevant date and personnel type columns?

**Comment by teixeirak** [comment]
I'd like to record crown.condition and crown.illum once per year.

**Comment by rudeboybert** [comment]
1. Thanks for the suggestions Jess. I moved the non-field variables `survey.ID, year, month, day, field.recorder, data.enter` to the far-right of the sheet
2. Per Krista's preference I've added `crown.condition, crown.illum` columns to the spring biannual survey (and only the spring survey)

Here is the updated [preliminary 2022 version](https://github.com/SCBI-ForestGEO/Dendrobands/blob/testing-2022/resources/raw_data/2022/data_entry_biannual_spr2022_BLANK.csv). Note I've moved it into the `2022` folder `resources/raw_data/2022/data_entry_biannual_spr2022_BLANK.csv` so computer technicians don't need to move the file, simply rename it by removing the `_BLANK`. I've also updated the [spring workflow instructions](https://github.com/SCBI-ForestGEO/Dendrobands/blob/testing-2022/resources/workflow_1_springbiannual_survey.md)

**Comment by jess-shue** [comment]
@teixeirak Are we recording `crown.condition` and `crown.illum` via the mortality survey in a way that would remove the need to collect that data during the dendro surveys? I'm thinking the `crown position` corresponds to `crown.illum`, but there may not be a proper correspondence to `crown.condition` as `percent crown intact` and `percent crown living` aren't a simple 1 through 5.

I don't see instructions on the categories/details for these columns within Dendrobands, but crown.illum definition = crown position found in the [mortality details](https://github.com/SCBI-ForestGEO/SCBImortality/blob/main/Protocols/Mortality-Protocol-2021.pdf), correct? It may be good to add notes to the [spring workflow instructions](https://github.com/SCBI-ForestGEO/Dendrobands/blob/master/resources/workflow_1_springbiannual_survey.md) that details what the 1-5 designations mean for both columns.

**Comment by teixeirak** [comment]
@jess-shue , you're right. 

`crown.illum` is a 5-class scale recorded for all trees in the mort census.

`crown position` is a 4-class scale (dominant, co-dominant, intermediate, suppressed) that we've been using for all the trees that die + some others (e.g., all cored trees).  

No good reason for two classification systems-- we adopted `crown.illum` with the dendrobands protocol from Helene & `crown position` from SERC (which means you probably are using both too...). It's annoying, but we now have long-term records of each and I don't want to disrupt either.  

`crown.illum` is the ariable that we've been collecting long-term for dendro bands, so that's the more important one. I think we can drop `crown position`.

**Comment by teixeirak** [comment]
There shouldn't be a need to collect `crown.illum` when measuring dendrobands **so long as we're confident that we'll get it as part of the mortality census**.  Likewise with `crown.condition` (I think).

My worry is that if we ever stop the mortality census (hope not!), we might forget to resume collecting this. Would it be tough to program in user response when running the script to create the spring dendro band census: "Will crown position and condition data be collected for all trees as part of the mortality census this year?". Then skip if answer is Y?

**Comment by teixeirak** [comment]
Okay, sounds good.

**Comment by rudeboybert** [comment]
Hey @teixeirak just to confirm, you want us to do `crown.illum` during biannual, but drop `crown.condition`?

(also mental note for Bert: `crown.position` is not a thing)

**Comment by teixeirak** [comment]
You know, it would be good to get crown.condition. It is repetitive with the mortality census, but as noted above, easier to just get it in the field (and useful for cross-checking).

**Comment by jess-shue** [comment]
OK, I want to make sure I have this correct! In the datasheets, there are columns for 'crown.illum' and 'crown.condition'. So just to confirm @teixeirak and @rudeboybert we will need to record the following:

`crown illumination`:  taken from the mortality census protocol which matches Gabriel Arellano's 2020 paper
5: tree leaves completely exposed to vertical light and to lateral light
4: full overhead light. ≥90% of the vertical projection of the crown exposed to vertical light.
3: some overhead light. 10-90% of the vertical projection of the crown exposed to vertical light.
2: lateral light. <10% of the vertical project of the crown exposed to vertical light, but the crown receives some light laterally.
1: no direct light at all. The crown receives only light filtered through the crowns of other trees.

`crown condition`:  Assess and record the crown condition of the tree using either the 4-point crown condition scale below or the % branch scale from the mortality census, as determined by site preferences and field team experience.  
The 4-point crown condition scale has the following categories:
4 = 75-100% of the crown is intact (no or few branches lost)
3 = 50-75% of the crown is intact
2 = 25-50% of the crown is intact
1 = 0-25% of the crown is intact (most of the crown is gone)

For this survey, I would like to include these definitions along with the list of codes in the field datasheet. My plan is to save the field sheet as an .xlsx file and add these definitions on a separate spreadsheet so everyone can reference them. I'll also add the `crown.illum` picture to the iPads.

**Comment by teixeirak** [comment]
Sounds great!

**Comment by rudeboybert** [comment]
Closed by #114
